######################################################################
# Automatically generated by qmake (2.01a) Sun May 10 00:11:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/xenoterracide/cropt/test/. .

# Input
HEADERS += connection.h
SOURCES += test.cpp
